### ISSUE TITLE
always come with link error 

### ISSUE THREAD

**Issue by 625673575** [Nelarius/imnodes#1]
**3>imnodes.obj** : error LNK2001: unresolved external symbol "public: static char const * const ImGuiTextBuffer::EmptyString" (?EmptyString@ImGuiTextBuffer@@2QBDB)
3>F:\Cpp\Falcor\Bin\x64\Release\MultiPassPostProcess.exe : fatal error LNK1120: 1 unresolved externals
**I have try to switch many different projects,and it turns out every of them has the same link issue.I spend 2 hours on it ,didn't find anything wrong.**

**Comment by Nelarius** [comment]
That's strange, imnodes itself doesn't use `ImGuiTextBuffer::EmptyString` for anything, it's an implementation detail of `ImGuiTextBuffer` 🤔 What version of ImGui are you using?

**Comment by 625673575** [comment]
@Nelarius  Using the lastest version,and finally I remove that part to make it work.
another useful function that I wonder how to implement is the range selection ,which enable us put an Rect struct param in to the function ,and return all the id of nodes and links.this could be useful for moving and removing

**Comment by Nelarius** [comment]
All right, glad to hear that you got it somehow working. I'll close this issue then, but if the problem persists then feel free to open a new issue 🙂 

Filtering nodes & links by rectangle actually sounds like a nice feature to have -- it's not possible via the API in `imnodes.h` right now, but shouldn't be that hard to implement. If you want, feel free to create a separate issue for that as well 😄

**Comment by Nelarius** [comment]
@625673575 Not sure if relevant anymore, but I went ahead and implemented the rectangle selector feature 😄 There can now be a number of nodes or links selected and once, and you can query the range of selected nodes or links:

![box_selector](https://user-images.githubusercontent.com/3276684/66500309-f74f3480-eac9-11e9-9acb-c755d9cc9eba.gif)
