### ISSUE TITLE
Multiple nodes can be selected by left-clicking

### ISSUE THREAD

**Issue by Nelarius** [Nelarius/imnodes#10]
Multi-node selection is half-baked at the moment: multiple nodes can be selected by left-clicking. The intention is to be able to click-select multiple nodes with a modifier pressed, e.g. shift.

![multinode_selection](https://user-images.githubusercontent.com/3276684/69912341-a9530f00-1430-11ea-86c9-0be5229f8830.gif)

**Comment by Nelarius** [comment]
Fixed in `def7754`.

**Comment by neverhood311** [comment]
What do you use for screen capture to GIF?

**Comment by Nelarius** [comment]
Using MacOS's built-in application window capture, cmd+shift+5. Pretty handy!
