### ISSUE TITLE
Node not respecting another elements mouse focus

### ISSUE THREAD

**Issue by mworzala** [Nelarius/imnodes#103]
Is there any way to stop the node from moving when I try to use the color input as seen in the video?

https://i.imgur.com/LKnfEwX.mp4

**Comment by void256** [comment]
I do have the same issue but I was able to work around it by changing https://github.com/Nelarius/imnodes/blob/0bcc9b77cba43da3eb625f16133d4b36fe6145b0/imnodes.cpp#L1470

to

```java
if (GImNodes->LeftMouseClicked && node_free_to_move && !ImGui::IsAnyItemActive())
```

which prevents selecting a Node when there is already any other item active.

This seems to work for me right now but I'm new to both Dear ImGui and imnodes so it's possible it breaks something else that I'm not aware yet 😉

**Comment by mworzala** [comment]
Fantastic, thanks for the work around :)

**Comment by Nelarius** [comment]
Thanks for the report. This was fixed in https://github.com/Nelarius/imnodes/commit/61c609a2ed5a4404b45137d21d9e7e48d125ee53. 👍
