### ISSUE TITLE
Add ability to disconnect a link by clicking and dragging

### ISSUE THREAD

**Issue by Nelarius** [Nelarius/imnodes#11]
In Blender it's possible to click and drag a link to disconnect it from a node, which is a very convenient feature. 

Current plans:
- [x] Left-click and drag to detach link (link detaching signalled via the `IsLinkDestroyed` function)
- [x] Add some kind of option for enabling/disabling "click and drag to detach"
- [x] Modifier + left-click over link to snap link wire to mouse cursor and detach link
- [x] Option for enabling/disabling "snap wire to mouse cursor"

**Comment by Nelarius** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ability to disconnect a link by clicking and dragging](https://trello.com/c/hqqURJTw/213-add-ability-to-disconnect-a-link-by-clicking-and-dragging)

**Comment by r-lyeh** [comment]
Also, in UE4:
- ALT+clicking on an input pin will disconnect current link and attach link to mouse cursor, so you can reconnect the link to some other input pin very quickly.
- ALT+clicking on an output pin will disconnect current link and attach link to mouse cursor, so you can reconnect the link to some other output pin very quickly.
- ALT+clicking on a bezier link will remove link plus all input/output connected pins.

**Comment by Nelarius** [comment]
The CTRL + click is a good idea - it would let you disconnect the wire/link while letting you drag new links from the pin 👍

**Comment by leifhelm** [comment]
Dragging from an output pin to reconnect could also be an option, if only one link can be connected to an output.

**Comment by Nelarius** [comment]
Hi @leifhelm! I'm not 100 % I understood what you mean. For two days now, it's possible to do this using the master branch:

![link_detach_demo](https://user-images.githubusercontent.com/3276684/79717279-d883f300-82e1-11ea-86d0-f40a9d6a1a2e.gif)

You can reconnect a detached link to any pin, and the link will be created again (i.e. `IsLinkCreated` will return true). Doing this is sort of broken in the color-node example though, I need to do a massive refactor to the code there 🙈

**Comment by leifhelm** [comment]
I was wondering if you could enable/disable this on a per attribute basis. This would enable multiple connections if they sould be possible. I plan on enabling one output to be distributed to many inputs but an input sould only have one connection.

PS: I too noticed that the examples are broken and not enable this. Furthermore, it is possible to right click outside of the windows in the examples and still open the context menu. (probably missing something like a `ImGui::IsWindowHovered()` check)

**Comment by Nelarius** [comment]
Okay yes, now I see! Yes, something like that could be done -- I was actually thinking about adding some sort of options for enabling/disabling this feature, exactly for the use-case you are talking about! But enabling it on a per-attribute basis is probably the most general way of doing it. 🙂 

> Furthermore, it is possible to right click outside of the windows in the examples and still open the context menu. (probably missing something like a ImGui::IsWindowHovered() check)

🙈 Noted, I will try to fix soon. Once I'm happy with some of the bigger changes here, I will try to rework that example.

**Comment by Nelarius** [comment]
Updated the parent comment with my current plans for detaching links.

**Comment by Nelarius** [comment]
All right, detaching by clicking and  dragging can be enabled on a pin-by-pin basis, and links can also be detached by left-clicking on them with a modifier pressed (the link wire will jump to the mouse cursor). Calling this done for now 🙂
