### ISSUE TITLE
Add picture inside of the node

### ISSUE THREAD

**Issue by aabilityuk** [Nelarius/imnodes#113]
Hi, first of all I want to thank the developers for efforts and spent time for lib dev! 

Is it possible to add picture to the node background and custom setup the pins distance and positions inside of the node?

If not, is there any plans in future to add this feature? 

Thank you!

**Comment by Nelarius** [comment]
Hi @aabilityuk !

Sorry about the slow response.

Images can be embedded in the node using `ImGui::Image()`, but that includes the image as a part of the node UI. Adding a custom background image to the node background isn't supported or planned at the moment, but I'm not against reviewing & merging PRs for the feature.

The following pin customization is supported.

*Pin offset*
```cpp
// Adjust the horizontal offset of the pin
ImNodes::GetStyle().PinOffset = 10.0f;
```

<img width="243" alt="Screenshot 2021-09-12 at 12 42 09" src="https://user-images.githubusercontent.com/3276684/132982882-64b64f94-f128-44b7-b97e-4f8bb4539348.png">

*Pin geometry*

You can select between six different pin geometries, as enumerated in `ImNodesPinShape_`. These are passed as an argument to `ImNodes::BeginInputAttribute` and `ImNodes::BeginOutputAttribute`.

<img width="243" alt="Screenshot 2021-09-12 at 12 45 47" src="https://user-images.githubusercontent.com/3276684/132982937-c2be5aa3-fa4a-4e3e-9653-e404d61b927c.png">
