### ISSUE TITLE
Minimap should work differently

### ISSUE THREAD

**Issue by smilediver** [Nelarius/imnodes#117]
Hi,

Right now, mini-map is basically the same thing as a zoomed out main editor view. IMHO, it would be much better if mini-map was a stationary overview of the whole graph. In short, it could:

* Show whole graph inside its view.
* Show a rectangle representing area visible inside the main editor view.
* Clicking on a mini-map would center main editor view to the selected area.

This way it would be a way to quickly navigate large graphs.

An example: https://help.screenberry.com/wp-content/uploads/2020/12/Navigator-Panel-1.gif

**Comment by qjj2857** [comment]
It would be nice as shown in the gif.
