### ISSUE TITLE
namespace collision reopened

### ISSUE THREAD

**Issue by sonoro1234** [Nelarius/imnodes#119]
@Nelarius
Regarding issue #97
Please, consider taking a look at this solution done by ImGuizmo: CedricGuillemet/ImGuizmo@e1049a9

**Comment by Nelarius** [comment]
Hi @sonoro1234 ! This seems like a good solution to the issue 👍

**Comment by smilediver** [comment]
I think define's name should be more unique, otherwise it could have the same issue as namespace. Maybe name it `NELARIUS_IMNODES_NAMESPACE`?
