### ISSUE TITLE
building problem SDL

### ISSUE THREAD

**Issue by Jules-NC** [Nelarius/imnodes#13]
Hi,
I am trying to build the project on Linux using `premake5 gmake`

When I do the `make`, I obtain the following error:
```
==== Building imgui (debug) ====
imgui_impl_sdl.cpp
../../imgui/imgui_impl_sdl.cpp:47:10: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
          ^~~~~~~
compilation terminated.
imgui.make:141: recipe for target 'obj/Debug/imgui/imgui_impl_sdl.o' failed
make[1]: *** [obj/Debug/imgui/imgui_impl_sdl.o] Error 1
Makefile:40: recipe for target 'imgui' failed
make: *** [imgui] Error 2
```

I tried to manually modify the imgui.make file to add `-I/usr/include/SDL` to the path but I only add many errors.

*I never used premake before, so it's totally probable that i'm doing something wrong here.*

**Comment by Nelarius** [comment]
Argh, seems like I hardcoded the SDL paths in `premake5.lua` to what I use on macOS 🙈 So the script simply isn't very good at the moment and could be refactored to take user-defined paths or something.

If you still want to try building the examples, you could try replacing the paths in the `includedirs` and `linkoptions` statetements
```
includedirs { "/Library/Frameworks/SDL2.framework/Headers" }
linkoptions { "-F/Library/Frameworks -framework SDL2 -framework CoreFoundation" }
```
with paths to your local SDL include and library directories.
