### ISSUE TITLE
Changed namespace name and removed MiniMap functionality

### ISSUE THREAD

**Issue by CyberPlaton** [Nelarius/imnodes#137]
Greetings developers,

as stated above, the imnodes Readme file should be updated to have the new namespace "imnodes" instead of "ImNodes".
Furthermore the Readme is misleading in showing the MiniMap functionality, where in the newest 0.4.0 Release it was removed.

**Comment by smilediver** [comment]
I think you're mixing readme files of different versions. Readme for 0.4 is here: https://github.com/Nelarius/imnodes/blob/v0.4/README.md . The one you see on the main page ( https://github.com/Nelarius/imnodes ) is for the latest version in progress, which wasn't released yet. I guess it's unfortunate that the 0.4 release is a bit outdated.

If you're using ImNodes library in your project, I suggest to take one directly from master branch to get all the latest features.
