### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by bigbigzxl** [Nelarius/imnodes#141]
Undefined symbols for architecture arm64:
  "_MTLCreateSystemDefaultDevice", referenced from:
      _METAL_CreateRenderer in libSDL2.a(SDL_render_metal.m.o)
  "_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
      objc-class-ref in libSDL2.a(SDL_render_metal.m.o)
  "_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
      objc-class-ref in libSDL2.a(SDL_render_metal.m.o)
  "_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
      objc-class-ref in libSDL2.a(SDL_render_metal.m.o)
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in libSDL2.a(SDL_render_metal.m.o)
  "_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
      objc-class-ref in libSDL2.a(SDL_render_metal.m.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../bin/Debug/colornode] Error 1
make: *** [colornode] Error 2

M1 macos;

**Comment by bigbigzxl** [comment]
m1 macos

**Comment by bigbigzxl** [comment]
config error.

**Comment by Nelarius** [comment]
Hi @bigbigzxl 👋  I removed the premake-based build system and migrated to CMake: 3ab867ddfe9e46437145b9b82c9ab7cb1fb9e06b. You could try building the examples again.

**Comment by bigbigzxl** [comment]
everything is fine on M1 based macos.
ths a lot~
