### ISSUE TITLE
How to free scaling node editor

### ISSUE THREAD

**Issue by key-with-board** [Nelarius/imnodes#146]
Hi i have a project use imnodes, i find if blueprint is more many in node editor not easy to operate.

So imnodes has this feature? if not what i can do.

**Comment by Nelarius** [comment]
Hi @key-with-board ! Scaling / zooming is being worked on in this pr: https://github.com/Nelarius/imnodes/pull/134

Consider using the `MiniMap` function to help you navigate around a large node graph in the editor in the meanwhile!

**Comment by key-with-board** [comment]
yes, im using this for now
