### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by GeTechG** [Nelarius/imnodes#147]
I really like your implementation, for its simplicity and at the same time complete. But alas, there are long-standing problems that are solved very slowly, and I thought maybe if it was possible to support financially, the work would go faster.

**Comment by Nelarius** [comment]
Thanks for the interest @GeTechG !

Right now donations wouldn't help make things go faster as my day job takes away a huge amount of time and energy at the moment, and unfortunately imnodes isn't involved in any way in my work. Once I have more time, I will consider this option!
