### ISSUE TITLE
Any plans on zooming?

### ISSUE THREAD

**Issue by kratochvil-jan** [Nelarius/imnodes#15]
Hi, are there any plans on implementing zooming? Asking if I should look into it myself.

**Comment by Nelarius** [comment]
No plans in the near future, so feel free to look into this yourself! Definitely would be a nice-to-have feature though 🙂

**Comment by r-lyeh** [comment]
FYI check out related answers originating from this comment :D https://github.com/ocornut/imgui/issues/772#issuecomment-244512595
