### ISSUE TITLE
Input / Output Attribute or input/output pins at same height

### ISSUE THREAD

**Issue by Atrix256** [Nelarius/imnodes#19]
This imgui node library is really nice!

In my setup, i have need to make an "input & output" attribute, where i give a label to something coming in to the node, which also then goes out of the node.

Alternately, if i could give a label to the input and none to the output, but have the pins show at the same height, that would solve my problem as well.

Is there a way to do this currently?

If not, does anyone have thoughts on how the code could be modified to do this?

Thanks!

**Comment by Atrix256** [comment]
I found that GetCursorPos() and SetCursorPos() are a good way to make this happen.

```
ImVec2 cpos = ImGui::GetCursorPos();

{
    const int input_attr_id = 2;
    imnodes::BeginInputAttribute(input_attr_id);
    ImGui::Text("Color Target");
    imnodes::EndAttribute();
}

ImGui::SetCursorPos(cpos);

{
    const int output_attr_id = 3;
    imnodes::BeginOutputAttribute(output_attr_id);
    ImGui::Text(" ");
    imnodes::EndAttribute();
}
```

**Comment by Nelarius** [comment]
Glad to hear you got it working, and thanks for sharing the code! 👍
