### ISSUE TITLE
Node width grows to infinity

### ISSUE THREAD

**Issue by gucio321** [Nelarius/imnodes#202]
Hi!
I try to implement wrapper of this project in [giu](https://github.com/allendang/giu) through [cimnodes](https://github.com/cimgui/cimnodes).

When I create a node I get something like this

https://github.com/user-attachments/assets/0b08bc0f-b5c5-46ab-9a2e-caab7713c746

I use docking branch of imgui. When I enable Viewports it crashes immediately.

**Comment by sonoro1234** [comment]
Difficult to know without code!!
Have you tried to mímic
https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/examples/imnodes_sample.lua

**Comment by gucio321** [comment]
@sonoro1234 here is my code:
```go
        basePos := imgui.MainViewport().Pos()
        imgui.SetNextWindowPosV(imgui.NewVec2(basePos.X+600, basePos.Y+460), imgui.CondOnce, imgui.NewVec2(0, 0)
        imgui.SetNextWindowSizeV(imgui.NewVec2(400, 200), imgui.CondOnce)
        imgui.Begin("Nodes demo")
        imnodes.BeginNodeEditor()

        imnodes.BeginNode(1)
        imnodes.BeginNodeTitleBar()
        imgui.Text("Node 1")
        imnodes.EndNodeTitleBar()
        imnodes.EndNode()

        imnodes.EndNodeEditor()
        imgui.End()
```

it results in crash:
```console
panic: Assertion failed!
	File: /home/runner/work/cimgui-go/cimgui-go/cwrappers/imgui/imgui.cpp, Line 11072
	
	Expression: 0 && "Code uses SetCursorPos()/SetCursorScreenPos() to extend window/parent boundaries. Please submit an item e.g. Dummy() to validate extent."	
```
When I set io.ConfigFlags to 0, it doesn't crash immediately but instead behaves like in the OP.

**Comment by sonoro1234** [comment]
At least it seems you need some attribute

```Lua
	ig.imnodes_BeginStaticAttribute(2)
        ig.PushItemWidth(120.0);
        ig.DragFloat("value", value, 0.01);
        ig.PopItemWidth();
        ig.imnodes_EndStaticAttribute();
```

**Comment by gucio321** [comment]
hehe, ok that makes sense, thank you!

**Comment by sonoro1234** [comment]
@Nelarius  I guess EndNode should assert on that!!
