### ISSUE TITLE
Clicking in other windows deselects nodes

### ISSUE THREAD

**Issue by Atrix256** [Nelarius/imnodes#22]
I have a property panel that shows info for the selected node, but whenever i click on the property panel, the selected nodes are cleared due to this code in EndNodeEditor() (like 1343)

```cpp
    // check to see if the mouse was near any node
    if (g.node_hovered == INVALID_INDEX)
    {
        if (is_mouse_clicked)
        {
            editor.selected_nodes.clear();
        }
    }
```

Changing the if to this fixes my issue.  Is this correct / should i submit a pull request?

```cpp
    // check to see if the mouse was near any node
    if (g.node_hovered == INVALID_INDEX && ImGui::IsWindowHovered())
    {
        if (is_mouse_clicked)
        {
            editor.selected_nodes.clear();
        }
    }
```

**Comment by Nelarius** [comment]
Good catch, that's definitely an annoying issue. The change you submitted will fix it -- although you should do it for `editor.selected_links` as well a few lines further down in the code. If you have the change lying around still, feel free to submit a pr! 👍

**Comment by Atrix256** [comment]
Ok cool thanks! I'll submit a PR

**Comment by Atrix256** [comment]
PR submitted: https://github.com/Nelarius/imnodes/pull/23
