### ISSUE TITLE
How to draw a rectangle between the background and nodes.

### ISSUE THREAD

**Issue by ketoo** [Nelarius/imnodes#24]
Hi,

I'd like to draw a rectangle with color by "ImGui::GetWindowDrawList()-AddRectFilled", and the layout of the rectangle should between the background and nodes.

Why do this?

Sometimes, we want to group some nodes as one group, to let the user know it clear, we would draw a background rectangle for these nodes.

May I know how to do that?

Thanks

**Comment by Nelarius** [comment]
This is one way of doing it. You need to create a draw list after `imnodes::BeginNodeEditor` and submit the draw calls (`AddRectFilled`, etc.) *before* you start a single node! In this way, all the nodes get rendered after the custom rectangle, and look like they are on top of it.

```cpp
imnodes::BeginNodeEditor();

ImDrawList* draw_list = ImGui::GetWindowDrawList();
draw_list->AddRectFilled(
    ImVec2(100, 100),
    ImVec2(400, 300),
    IM_COL32(200, 200, 200, 100));

imnodes::BeginNode(1);
imnodes::BeginNodeTitleBar();

// the rest of the node, etc..
```

<img width="440" alt="image" src="https://user-images.githubusercontent.com/3276684/76059266-0ce85d80-5f87-11ea-8297-74741b683326.png">

There is one drawback: you probably need to know the size of the rectangle based on the nodes themselves. But you don't know where the nodes are going to be until you render them! One solution is to render the rectangle based on the nodes of the *previous* frame, but this means that if the nodes are moved around the rectangle might be a bit laggy.

**Comment by ketoo** [comment]
Thanks, this way is a cheap way to meet the goal. About the size of the rect, it's fine as the application has the position of all nodes. The only issue is the rect's position is not the saome coordinate system with imnodes, need to do an extra job to fix this. If imnodes can provide two interfaces as below would be great:

void AddRect(const ImVec2& p_min, const ImVec2& p_max, ImU32 col, float rounding, ImDrawCornerFlags rounding_corners, float thickness);

void AddRectFilled(const ImVec2& p_min, const ImVec2& p_max, ImU32 col, float rounding, ImDrawCornerFlags rounding_corners);

Actually I want to do this job and do a PR, but unfortunately, I can't do this job as I have not understood imnodes's coordinate system very clean.

**Comment by Nelarius** [comment]
I saw you opened the pr for fetching the panning value, I guess that solves the problem for now? 🙂

**Comment by ketoo** [comment]
Yes, now meet the goal, thanks for your help!
