### ISSUE TITLE
Move grid will move when scroll the mouse's mid key.

### ISSUE THREAD

**Issue by ketoo** [Nelarius/imnodes#26]
The image below shows the issue.

![image](https://user-images.githubusercontent.com/5752768/76159069-9cf1f700-6181-11ea-9d15-a01029a26240.png)

A way to meet this issue with 100%:

If you moved a node out of the window, then scroll your mouse mid key, the issue will come.
![image](https://user-images.githubusercontent.com/5752768/76159173-87310180-6182-11ea-8d82-6100d1116f50.png)

**Comment by Nelarius** [comment]
Thanks for reporting the issue, I was able to reproduce it as well! Really weird issue, since I don't use the mouse scroll wheel for anything 🤯
