### ISSUE TITLE
Linking Errors

### ISSUE THREAD

**Issue by brionholland** [Nelarius/imnodes#29]
I'm getting the below linking errors when I attempt to include imnodes in my project.  I can include the files and it recognizes the functions but won't compile them.  ImGui works fine when I don't attempt to use imnodes.  Any thoughts.

Thanks!

`VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::Initialize(void)" (?Initialize@imnodes@@YAXXZ) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)
1>VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::Shutdown(void)" (?Shutdown@imnodes@@YAXXZ) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)
1>VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::BeginNode(int)" (?BeginNode@imnodes@@YAXH@Z) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)
1>VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::EndNode(void)" (?EndNode@imnodes@@YAXXZ) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)
1>VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::BeginOutputAttribute(int,enum imnodes::PinShape)" (?BeginOutputAttribute@imnodes@@YAXHW4PinShape@1@@Z) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)
1>VisualState.obj : error LNK2019: unresolved external symbol "void __cdecl imnodes::EndAttribute(void)" (?EndAttribute@imnodes@@YAXXZ) referenced in function "public: void __cdecl VisualState::VisualZone(void)" (?VisualZone@VisualState@@QEAAXXZ)`

**Comment by quesnel** [comment]
Have you add both `imnodes.h` and `imnodes.cpp` to your project?

**Comment by brionholland** [comment]
yes, I have them both in the project.  everything is recognized just fine in that I can compile.  But when when it tries to build/execute it seems to not be able to understand the links.

**Comment by quesnel** [comment]
Given the names of the symbols you use Visual Studio but do you use CMake (I don't know VS)?

**Comment by brionholland** [comment]
I do use cmake.

**Comment by quesnel** [comment]
Can you show your `CMakeLists.txt` which included these files?

**Comment by brionholland** [comment]
ohh, sorry, I misunderstood.  I didn't use CMake to bring the files in.  I cloned the project and then pointed my includes directory as the folder.

**Comment by quesnel** [comment]
No problem.Good continuation!

**Comment by Nelarius** [comment]
Hi @brionholland ! You said that you pointed your includes directory at the imnodes folder. But did you compile `imnodes.cpp` and link against the resulting static library?

Imnodes unfortunately isn't a header-only library, so it's not enough to just copy-paste the files in to the project and include them (although I think my README does say " just copy-paste ... into your project. " , I should probably rephrase that 😅 )

**Comment by brionholland** [comment]
ahhh, yep, that was it.  Thanks for the help!

**Comment by Nelarius** [comment]
Glad to hear it worked out! 👍
