### ISSUE TITLE
Screen only renders in lower left corner

### ISSUE THREAD

**Issue by marcizhu** [Nelarius/imnodes#3]
I've tried to compile & run this app on macOS but unfortunately it looks like this:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/6199781/69572434-68886f80-0fc4-11ea-97fb-ed625705095b.png">
As you can see, the display is only shown on the lower left corner as if it was the entire screen, and dragging/resizing any window outside that quarter is impossible (it disappears as if I was moving the window outside the visible screen). However the mouse input detects the entire screen, which makes it rather difficult to interact with the imgui windows, as I have to click and drag where there's nothing.

My guess is that the high-dpi screen affects the rendering somehow.
Hope to get this fixed soon! The library looks awesome, good job!

**Comment by Nelarius** [comment]
Huh, that is a weird issue. It looks like the window is completely cut off on the right! Do you have external monitors attached (with a different dpi)?

The examples are a bit quick and dirty, to be honest 😅 So I have a hunch that my example code is maybe doing something idiotic in handling window resizing or something. I will have to take a look and see if I can repro this!

**Comment by marcizhu** [comment]
I don't have any external monitors or anything like that, just the laptop's screeen but as I said, it is high dpi and I'm guessing that might be the culprit.

**Comment by Nelarius** [comment]
I wasn't able to repro it locally, but I think you're right. I enabled hi-dpi rendering in the examples, and changed the way the viewport size is calculated (which is what I suspect was buggy) in the commit `6e0eee4`. Hope it works better now!

**Comment by marcizhu** [comment]
Yup, fixed!!
Thank you for fixing this sooo quick! :D
