### ISSUE TITLE
SDL dependency missing

### ISSUE THREAD

**Issue by rytisss** [Nelarius/imnodes#31]
In the example project, SDL is missing. Would it be possible to add?

**Comment by Nelarius** [comment]
Sure! The build script is in an inconsistent state, it essentially works on my machine and the CI server. It could be much better 😕

**Comment by Nelarius** [comment]
Played around with copy-pasting SDL2 into the project, but it's just not very practical -- you need multiple copies of SDL2 for every platform 🤦 Instead, you should install SDL2 via a package manager (like `vcpkg`, or just install the SDL2 framework if you are on MacOS). Master has been updated, and you can now do this:

```bash
$ premake5 gmake \
    --sdl-include-path=/Users/nelarius/vcpkg/installed/x64-osx/include/SDL2 \
    --sdl-link-path=/Users/nelarius/vcpkg/installed/x64-osx/lib
```

Or alternatively this, if on MacOS with the SDL2 framework:
```bash
$ premake5 gmake --use-sdl-framework
```

Should be a bit more flexible!
