### ISSUE TITLE
Box Selection when window is not focused/hovered

### ISSUE THREAD

**Issue by leifhelm** [Nelarius/imnodes#32]
When the window with the node editor is covered by another window and the other window gets dragged, a box selection appears in the node editor window.
One might add a check for `ImGui::IsWindowHovered()`.
This code in `EndNodeEditor()` fixes this behavior: 
 ```
const bool is_mouse_clicked_in_canvas =
            is_mouse_clicked &&
            ImGui::IsWindowHovered() &&
            g.canvas_rect_screen_space.Contains(ImGui::GetMousePos());
```

**Comment by Nelarius** [comment]
Thanks for catching this, I added a check for `IsWindowHovered` 👍
