### ISSUE TITLE
Crashes when selecting a link overlapping a node

### ISSUE THREAD

**Issue by leifhelm** [Nelarius/imnodes#33]
When clicking on a link that is above a node the assert `assert(editor.click_interaction_type == ClickInteractionType_None);` fails. 
### Steps to repoduce ###
Add three nodes. Connect two. Then move the third under the link and click on the link.
![grafik](https://user-images.githubusercontent.com/31693262/79688806-0b31db00-8251-11ea-85c5-3ad3457538d0.png)
Note the sizes of are off because i use a 32pt font.

**Comment by Nelarius** [comment]
Thanks for reporting again! 👍I fixed this by just removing the assert in question. Now clicking a link over a node results in just the link being selected, which I think makes sense.
