### ISSUE TITLE
Overlapping node selection

### ISSUE THREAD

**Issue by leifhelm** [Nelarius/imnodes#36]
I noticed some wierd selection behaviour if two nodes overlap:
![overlapping nodes](https://user-images.githubusercontent.com/31693262/80735100-7c567580-8b10-11ea-9d95-c4e448c69e8c.gif)
The node in the foreground is not selected but rather the node that was first created (with the lower id I guess).

**Comment by Nelarius** [comment]
Right, this is the result of a known bug: the nodes don't have any concept of order or depth. This results in buggy selection. Thanks for illustration, hadn't really thought about what this means for selection of overlapping nodes!

**Comment by Nelarius** [comment]
Progress on improved event handling and rendering of nodes 🙂 Node depth order is now taken in to account.

![more_overlapping_nodes](https://user-images.githubusercontent.com/3276684/89120461-34543f80-d4bf-11ea-88c2-4cedef8750fa.gif)

**Comment by Nelarius** [comment]
This should no longe be a problem with the latest `master` branch 🙂
