### ISSUE TITLE
BUG: Crash on link creation

### ISSUE THREAD

**Issue by PossiblyAShrub** [Nelarius/imnodes#48]
If I were to set up my node editor such that I draw a node, then a link, and then more nodes, like in the pseudo-code below, creating a second link, and only a second link, causes an assert - crashing the whole app. I have found 2 solutions to this issue which are also below.

## The Problem
I store links within my nodes, so to simplify things I wrote something like below:
```c++
for (auto node : nodes)
{
	imnodes::BeginNode(node.id);
  // draw node things
	imnodes::EndNode();

	for (auto links : node.links)
	{
		// draw link
		imnodes::Link(link.id, link.start_id, link.end_id);
	}
}
```
However, because I intertwine nodes and links I get,
![crash](https://user-images.githubusercontent.com/46799759/87842885-d5f35400-c864-11ea-9362-7d16e2a7f388.gif)

## The solution(s)
1. Don't intertwine nodes and links (ie. draw all nodes, and then draw all links)
2. Change the following line in *imnodes.cpp*'s `click_interaction_update` function, and under the link creation case
```c++
if (snapping_pin_changed && g.snap_link_idx.has_value())
```
to
```c++
if (snapping_pin_changed && g.snap_link_idx.has_value()
    && editor.click_interaction_state.link_creation.end_pin_idx.has_value())
```

**Comment by Nelarius** [comment]
I suppose you're getting an assert in `OptionalIndex::value()`? If `snap_link_idx` has a value, then it is an error for `end_pin_idx` to **not** have a value, and there's a bug in the code somewhere 🤔 

It should actually be OK to intertwine nodes and links, since link rendering is actually now deferred until `EndNodeEditor`. I need to update the documentation on that.

**Comment by Nelarius** [comment]
Hi @PossiblyAShrub ! Wasn't able to reproduce this problem, but I just pushed the commit `4ccf2f1` to master. It adds the `end_pin_idx.has_value()` check to, IMO, the correct place: `snapping_pin_changed` will be false when `!end_pin_idx.has_value()`. Can you check if it solves your issue?

**Comment by PossiblyAShrub** [comment]
Sure! I’m out of town for the weekend, but on Monday I’ll check.

**Comment by PossiblyAShrub** [comment]
I just tested the new commit. Everything seems to be working! Thank you for your time :)
