### ISSUE TITLE
Enhancement: Add example for node removal

### ISSUE THREAD

**Issue by beyonik** [Nelarius/imnodes#49]
There currently aren't any examples showing how to remove a node and all links connected to it's attributes.

**Comment by Nelarius** [comment]
Hi @beyonik !

The example contained in `color_node_editor.cpp` does feature node and link deletion. Of course, that example contains a bunch of other functionality as well, so it may not be the easiest to follow. Do you think it would be better to have a simpler example showing only how node and link removal works?

**Comment by beyonik** [comment]
> Hi @beyonik !
> 
> The example contained in `color_node_editor.cpp` does feature node and link deletion. Of course, that example contains a bunch of other functionality as well, so it may not be the easiest to follow. Do you think it would be better to have a simpler example showing only how node and link removal works?

Oh, I didn't notice that even though thats where I first looked, but I guess that proves my point. A seperate example could be useful but I guess a bit redundant, so at this point it's up to you to decide if it's worth making a seperate example.

**Comment by Nelarius** [comment]
Yeah, it's not very clear at the moment what is contained in the examples. I've added an item to my todo list to improve the documentation 🙂
