### ISSUE TITLE
Typo in README tutorial

### ISSUE THREAD

**Issue by neverhood311** [Nelarius/imnodes#5]
In the README, I think there's a typo. In the section about creating an output attribute, you have the following code snippet:
```
...
ImGui::Text("output pin");
ImGui::EndAttribute();

imnodes::EndNode();
...
```

I believe it should be:
```
...
ImGui::Text("output pin");
imnodes::EndAttribute();   // this should be imnodes, not ImGui

imnodes::EndNode();
...
```

**Comment by Nelarius** [comment]
Thanks for spotting that! 🙂 This is now fixed.
