### ISSUE TITLE
Default arguments on pointers for C binding

### ISSUE THREAD

**Issue by sonoro1234** [Nelarius/imnodes#62]
I have done a C wrapping of imnodes in https://github.com/cimgui/cimnodes

It would be much better for default arguments on pointers to be NULL than 0

```C++
bool IsLinkCreated(
    int* started_at_attribute_id,
    int* ended_at_attribute_id,
    bool* created_from_snap = NULL);
```

Would you mind doing this changes?

**Comment by Nelarius** [comment]
Really cool contribution @sonoro1234 ! 👍  Should be an easy enough change to make.
