### ISSUE TITLE
Box selection triggers when moving the ImGui window that contains the node editor

### ISSUE THREAD

**Issue by neverhood311** [Nelarius/imnodes#7]
Create a window and put a node editor inside. Run the program. If you click in the window top bar then drag it up and left, a selection box appears inside the node editor. I didn't expect a box selection tool when I clicked and dragged somewhere outside the node editor.

Edit: this also happens if you click and drag somewhere outside the ImGui window. For example, click and drag from just outside the right side of the window up to just above the top of the window. A selection box will appear in the node editor.

**Comment by Nelarius** [comment]
Nice catch, that's definitely not intended.
