### ISSUE TITLE
Issue with dlls

### ISSUE THREAD

**Issue by bootzin** [Nelarius/imnodes#74]
Would it be possible to add a public method similar to the one below?

```
void SetImGuiContext(ImGuiContext* ctx) {
    ImGui::SetCurrentContext(ctx);
}
```

The reason behind this is that globals are not shared between dlls, so when compiling imgui into a dll and imnodes into another, the context is not shared, and I end up getting access violations

You can read more about this [here](https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam)

I can also submit a PR to this if you wish, but I'm not exactly familiar with c++, although it does seems like an easy change

**Comment by Nelarius** [comment]
Hi @bootzin ! Sorry for taking a long time to respond. I must confess that I haven't worked very much dlls 😅But I think I understood the gist: you need a function exported from the imnodes dll which would set the `GImGui` global in that module.

I checked ImPlot, another ImGui extension library, and it seems like they also have exposed a `SetImGuiContext` function as part of the library API. So I don't see why `imnodes` wouldn't have it either.
