### ISSUE TITLE
We can still make a link between two nodes even if there is a node over one of them.

### ISSUE THREAD

**Issue by Moi78** [Nelarius/imnodes#77]
I leave this pic as it explains everything by itself.
![capture_issue](https://user-images.githubusercontent.com/19874518/101996329-d25be000-3cd1-11eb-825f-4f7868a0d545.png)

**Comment by Nelarius** [comment]
Fix merged in 50a696d1c8a22ad25e2a84d8a9fb1a181d5b60da
