### ISSUE TITLE
AddBezierCurve -> AddBezierCubic

### ISSUE THREAD

**Issue by sonoro1234** [Nelarius/imnodes#78]
While testing future LuaJIT-ImGui release I had a compiling error for imnodes.

It is caused by a function renaming that will take place in v1.80:
https://github.com/ocornut/imgui/commit/4d8e839ddf3786f11390002b86218419311843fb

Perhaps `IMGUI_VERSION_NUM` could be used for calling one or the other?

**Comment by Nelarius** [comment]
Thanks for bringing this issue up! 👍
