### ISSUE TITLE
Node remains selected after click and drag

### ISSUE THREAD

**Issue by neverhood311** [Nelarius/imnodes#8]
Disclaimer: Not sure if this is a bug or a feature, but it's not consistent with other node editors I've used.

Create a node editor and put two nodes in it. Click and drag one of them to move it. Now click and drag the other one. The first one remained selected so they both move when you try to move the second one.

I expected to be able to move each node individually without having to deselect each after moving them.

**Comment by Nelarius** [comment]
Moving both selected nodes at once is intentional. But being able to select another node after one already is selected is not intentional. I actually just created an issue for that: #10 .

**Comment by Nelarius** [comment]
Fixed in `def7754`. Now you don't need to deselect nodes when clicking on a new one.
