### ISSUE TITLE
Links with glew instead of gl3w by default

### ISSUE THREAD

**Issue by vyorkin** [Nelarius/imnodes#86]
Hello! I'm trying to build imnodes on Ubuntu 20.4. Here is what I do:

```sh
 premake5 gmake --sdl-include-path=/usr/include/SDL2 --sdl-link-path=/usr/lib
```

But I'm getting the linking errors:

```sh
/usr/bin/ld: ../../lib/Debug/libimgui.a(imgui_impl_opengl3.o): in function `ImGui_ImplOpenGL3_Init(char const*)':
/home/vyorkin/projects/github/cxx/imnodes/build/gmake/../../dependencies/imgui-1.80/imgui_impl_opengl3.cpp:160: undefined reference to `glGetIntegerv'
/

...

pl_opengl3.cpp:716: undefined reference to `__glewDeleteProgram'
collect2: error: ld returned 1 exit status
```

https://asciinema.org/a/Blq2Vpo40uu7KZsHrIpgaVVpo

**Comment by Nelarius** [comment]
Hi @vyorkin ! Strange error, as the CI pipeline for this project runs in a ubuntu image, and doesn't seem to suffer from the same problem 🤔 I don't have access to ubuntu right now, but looking at the premake5.lua script, I can see that on Linux, we only do:

```lua
    filter "system:linux"
        links { "dl" }
```

Maybe we should also be linking agains `-lgl`? Could you try if modifying the script to this helps?
```lua
    filter "system:linux"
        links { "dl", "gl" }
```

**Comment by vyorkin** [comment]
Thanks, @Nelarius, yes you're right, it linking succeeds if I change it to:
```
    filter "system:linux"
        links { "dl", "GL", "GLEW }
```

Now I have another problem (segfault), which I'm trying to debug, here is the backtrace from gdb:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055e513fcedc5 in ImGui_ImplOpenGL3_CreateDeviceObjects () at ../../dependencies/imgui-1.80/imgui_impl_opengl3.cpp:669
#2  0x000055e513fcdd09 in ImGui_ImplOpenGL3_NewFrame () at ../../dependencies/imgui-1.80/imgui_impl_opengl3.cpp:242
#3  0x000055e513f7469a in main () at ../../example/main.cpp:92
```

**Comment by vyorkin** [comment]
I think it is related to #83
