### ISSUE TITLE
Node overlap rendering is not correct

### ISSUE THREAD

**Issue by Nelarius** [Nelarius/imnodes#9]
When dragging nodes over each other, the rendering is glitchy due to all node frames being rendered in a loop in `EndNodeEditor`. It would be better to render the frame after `EndNode` is called so that the node frame and ImGui UI are at least rendered in the same order.

![node_overlap_rendering_problem](https://user-images.githubusercontent.com/3276684/69912319-4e211c80-1430-11ea-9ad0-c8381c66de2f.gif)

**Comment by Nelarius** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Node overlap rendering is not correct](https://trello.com/c/jS9cfVgf/212-node-overlap-rendering-is-not-correct)

**Comment by ketoo** [comment]
Meet the same issue.

**Comment by NukeBird** [comment]
are there any improvements?

**Comment by Nelarius** [comment]
Not yet 😞 I think I am going start working on this issue next week, going to try to fix a few other fundamental issues as well.

**Comment by ketoo** [comment]
Great, please let me know if you need any help that comes from other developers.

**Comment by NukeBird** [comment]
Cool! Keep it up, I really love your lib! 
It's pretty simple in comparison with others

**Comment by Nelarius** [comment]
Thanks, happy to hear that you think so! 😊

**Comment by Nelarius** [comment]
All right, finally made some progress on this. Now nodes are nicely rendered on top of each other if they overlap. It's not perfect though: clicking and dragging a node doesn't put it in top of other nodes automatically -- the "depth order" depends on which order you called `BeginNode`/`EndNode`. It would be nice to have more control over the depth order of the node draw commands, but that's another issue. I will close this issue 🙂 

@ketoo I had to delete `IsAttributeLinked` and therefore remove the pin linked/unlinked rendering 😞  Really sorry for breaking the feature so soon after you wrote it! To fix the overlap issue, I had to move`draw_node` and `draw_pin` from `EndNodeEditor` to `EndNode()`, which meant that the link connectivity information is no longer available at that point. So the pins are back to being simple filled shapes for now. One of the drawbacks of being an immediate mode UI is that you have to throw the state away at the end of every frame 😬

**Comment by ketoo** [comment]
> All right, finally made some progress on this. Now nodes are nicely rendered on top of each other if they overlap. It's not perfect though: clicking and dragging a node doesn't put it in top of other nodes automatically -- the "depth order" depends on which order you called `BeginNode`/`EndNode`. It would be nice to have more control over the depth order of the node draw commands, but that's another issue. I will close this issue 🙂
> 
> @ketoo I had to delete `IsAttributeLinked` and therefore remove the pin linked/unlinked rendering 😞 Really sorry for breaking the feature so soon after you wrote it! To fix the overlap issue, I had to move`draw_node` and `draw_pin` from `EndNodeEditor` to `EndNode()`, which meant that the link connectivity information is no longer available at that point. So the pins are back to being simple filled shapes for now. One of the drawbacks of being an immediate mode UI is that you have to throw the state away at the end of every frame 😬

No worry, I can manage the pin's status in my application. To do this, I need the the pin system can support more shapes such as the solid triangle and the hollow triangle, which can meet the same goal.

**Comment by Nelarius** [comment]
Yeah, my application also has the connectivity information. So what we now need is to be able to set per-pin style, and allow the pin shape style to be hollow or filled 👍

**Comment by ketoo** [comment]
Great, thats enough for the developer.

**Comment by Nelarius** [comment]
I added filled/unfilled shapes to master.

**Comment by ketoo** [comment]
Cool! I updated and it works. But I meet a new issue when I run the application on MAC, listed as below:

`2020-02-12 22:33:12.564071+1300 NFServerEx[3896:24567] [NFServerEx] CGContextFillRects: invalid context 0x0. Backtrace:
  <CGContextFillRect+105>
   <NSRectFill+237>
    <-[SDLView drawRect:]+114>
     <-[_NSOpenGLViewBackingLayer display]+901>
      <_ZN2CA5Layer17display_if_neededEPNS_11TransactionE+627>
       <_ZN2CA7Context18commit_transactionEPNS_11TransactionE+342>
        <_ZN2CA11Transaction6commitEv+596>
         <__65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke+274>
          <__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__+23>
           <__CFRunLoopDoObservers+451>
            <__CFRunLoopRun+1136>
             <CFRunLoopRunSpecific+455>
              <RunCurrentEventLoopInMode+292>
               <ReceiveNextEventCommon+355>
                <_BlockUntilNextEventMatchingListInModeWithFilter+64>
                 <_DPSNextEvent+1135>
                  <-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]+1361>
                   <Cocoa_PumpEvents+104>
                    <SDL_PumpEvents_REAL+45>
                     <SDL_WaitEventTimeout_REAL+53>
                      <SDL_PollEvent_REAL+23>
                       <SDL_PollEvent+36>
                        <_ZN10NFUIModule7ExecuteEv+68>
                         <_ZN9NFIPlugin7ExecuteEv+89>
                          <_ZN15NFPluginManager7ExecuteEv+141>
                           <_ZN14NFPluginServer7ExecuteEv+45>
                            <main+2635>        `

**Comment by Nelarius** [comment]
Looks like something fails deep inside OpenGL 😯 Are you sure it was imnode's triggering this crash? imnodes itself doesn't touch window resize logic, nor did the pin rendering changes have anything to do with UI event handling 🤔

**Comment by ketoo** [comment]
I have done a test, the result shows that the issue comes from Imgui itself.
