### ISSUE TITLE
Snapping to grid, primary grid line coloration

### ISSUE THREAD

**Issue by Nelarius** [Nelarius/imnodes#98]
@Web-eWorks made a nice implementation for snapping nodes to the grid: https://github.com/Nelarius/imnodes/pull/72 Opening this issue, so the work doesn't get lost.

The pr would need some work due to merge conflicts. I think it also might be worth experimenting if the snapping the nodes to the grid while clicking and dragging would be a better experience.

**Comment by Web-eWorks** [comment]
I've not had time to make the final changes to the linked PR so far, but I'll hopefully be able to knock that out over the weekend or next week.

**Comment by munshkr** [comment]
I took the liberty of rebasing the branch by @Web-eWorks against the current master and solve some conflicts, and it seems to be working fine :) Just wanted to mention this in case someone wants to use it now, even if it's experimental and needs some refactoring. Branch is [here](https://github.com/munshkr/imnodes/tree/grid-snapping).

**Comment by Nelarius** [comment]
Really cool to see the branch getting updated @munshkr ! 🙌 Would you have any interest in submitting a pr containing the snap-to-grid changes? I am going to spend some time with Imnodes later this week and could take a look at a new pr.

**Comment by Web-eWorks** [comment]
The existing PR has been rebased and updated, thanks @munshkr for reviving interest in this branch! I've added a few minor UX features as well and addressed all outstanding feedback on the branch (as well as updated the build tooling to allow the examples to be build under Linux).
